# Generated by Django 5.0.4 on 2024-04-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="sub_places",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_place", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
            ],
        ),
    ]
