# Generated by Django 5.0.4 on 2024-04-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_app", "0003_travelling_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelling_user",
            name="date_from",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="travelling_user",
            name="date_to",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="travelling_user",
            name="no_of_travellers",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="travelling_user",
            name="sub_places",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
