# Generated by Django 5.0.4 on 2024-04-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "travel_app",
            "0004_travelling_user_date_from_travelling_user_date_to_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="profile_photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "photo",
                    models.ImageField(
                        default="user_photos/default.jpg", upload_to="user_photos/"
                    ),
                ),
            ],
        ),
    ]
