# Generated by Django 5.0.4 on 2024-04-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_app", "0005_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile_photo",
            name="photo",
            field=models.ImageField(
                default="user_photos/default.jpg", upload_to="media/"
            ),
        ),
    ]
