# Generated by Django 5.0.4 on 2024-04-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_app", "0007_alter_profile_photo_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="place",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
