# Generated by Django 5.0.4 on 2024-04-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_app", "0009_auto_20240410_1300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile_photo",
            name="photo",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
