# Generated by Django 5.0.4 on 2024-04-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0007_alter_profile_photo_photo'),
        ('travel_app', '0010_alter_profile_photo_photo'),
    ]

    operations = [
    ]
