# Generated by Django 5.0.4 on 2024-04-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_app", "0011_merge_20240414_1851"),
    ]

    operations = [
        migrations.CreateModel(
            name="remainder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=30)),
                ("date", models.DateField(null=True)),
                ("note", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
